### ISSUE TITLE
Bug: `explain` type is incorrect in `History` factory

### ISSUE THREAD

**Issue by clementjumel** [aphp/edsnlp#116]
Hi! I find your work with `edsnlp` really cool, and I'm working on integrating it in one of our tools at [Arkhn](https://arkhn.org/) 🙂 
I found a very little mistake which prevents us from trying the `History` component at all and which should be very easy to fix!

## Description

In the History class, you use an attribute `explain`, which is a boolean, however in the corresponding factory, you made it a string (right [here](https://github.com/aphp/edsnlp/blob/65b491bd7d4c3a3c56773f2ddd894c570aa1564a/edsnlp/pipelines/qualifiers/history/factory.py#L49)). 

As a consequence, spaCy converts the parameter to a string, so the "explain mode" is always on, which is an issue when we try to serialize the documents (e.g. with `doc.to_bytes()`) as the history cues are not serializable. 😬

## How to reproduce the bug

```python
import spacy

nlp = spacy.blank("fr")
nlp.add_pipe("eds.history")

name, component = nlp.pipeline[-1]
print(name)
print(component.explain)
print(type(component.explain))
print(bool(component.explain))
```
which gives:
```
eds.history
False
<class 'str'>
True
```
the last line exhibits that the explain feature [here](https://github.com/aphp/edsnlp/blob/65b491bd7d4c3a3c56773f2ddd894c570aa1564a/edsnlp/pipelines/qualifiers/history/history.py#L233) is always activated 😕

## Your Environment

- Operating System: MacOS
- Python Version Used: 3.9.13
- spaCy Version Used: 3.1.3
- EDS-NLP Version Used: 0.6.2
- Environment Information:

**Comment by percevalw** [comment]
Hi @clementjumel, thanks for using the library and letting us know about this issue! Would you like to submit a PR to fix this?

**Comment by clementjumel** [comment]
> Hi @clementjumel, thanks for using the library and letting us know about this issue! Would you like to submit a PR to fix this?

Sure, here it goes: #117 🙂

For some reason, locally, not all tests were passing before & after the change, even following the installation described [here](https://github.com/aphp/edsnlp/blob/master/contributing.md). 😬
Besides, given the nature of the fix, I don't think it's worth the implementation of tests for the fix!
