### ISSUE TITLE
Feature request: custom qualifier patterns

### ISSUE THREAD

**Issue by clementjumel** [aphp/edsnlp#118]
## Feature type

Modification of pipelines

## Description

Hi 🙂

We're considering migrating from [negspacy](https://github.com/jenojp/negspacy), that we use for instance with termsets adapted from [French Fast Context](https://github.com/practikpharma/FrenchFastContext), to edsnlp, in order to perform assertion status detection, so I had a suggestion about your [qualifier components](https://github.com/aphp/edsnlp/tree/master/edsnlp/pipelines/qualifiers), that I find really cool btw! 

I was wondering about the reason(s) why you chose to load the default patterns of the qualifiers during their initializations, compared to include the default patterns as the factory default parameters? I guess on the "pro" side of adding the default patterns during the initialization (your approach), I can see that it's more user-friendly (it's simpler to add new patterns), but on the "con" side, we cannot use entirely custom patterns (since we cannot remove the default patterns), therefore it gives less room to users to optimize the patterns to their own use-cases, if I got that correctly

Is there another reason why you made this design choice? If not, would you be open to change the way the default patterns are working? (this could be done with a parameter that indicates whether or not to add the default patterns to the ones in the parameters for instance, if you want to bring less radical changes to the existing code base) 

PS: looking into this, I found what I believe to be a very minor issue in the `History` component factory, [here](https://github.com/aphp/edsnlp/blob/d72b2972c00382d326c782e3633a8d798ed9df97/edsnlp/pipelines/qualifiers/history/factory.py#L11), in the `DEFAULT_CONFIG`, you use not None values for `history` and `termination` but these values are useless since they are duplicates of the component's `defaults` class attribute (in the other qualifiers the corresponding parameters are correctly set to None)

**Comment by percevalw** [comment]
Hi ! Indeed, the way we load the qualification templates doesn't quite follow the schema of other pipelines, we could change that! However, I'm not quite sure I understand your use case: do you want to overwrite the existing negation patterns? I believe the current version allows this by setting the relevant parameters in the pipeline configuration as follows:

```python
nlp = spacy.blank('eds')
nlp.add_pipe("eds.sentences")
nlp.add_pipe("eds.matcher", config={"terms": {"thrombose": ["thrombose"]}})
nlp.add_pipe("eds.negation", config={
    "pseudo": [],
    "preceding": ["encore"],
    "following": [],
    "termination": [],
    "verbs": [],
})

doc = nlp("Encore une thrombose. Pas de thrombose.")
print(doc.ents[0]._.negation)
# True
print(doc.ents[1]._.negation)
# False
```

Would this match your use case ?

**Comment by clementjumel** [comment]
> I'm not quite sure I understand your use case: do you want to overwrite the existing negation patterns? I believe the current version allows this by setting the relevant parameters in the pipeline configuration as follows

Oh my mistake, you're right, I got confused with `terms.update(kwargs)`! For some reason I was considering that this would _append_ the stuff from `kwargs` to `terms` whereas you're right, it does overwrite it, sorry about that 😬

The (very little) remark above on a minor inconsistency of the history factory still stands, but it's very unimportant so I guess we can close this?

**Comment by percevalw** [comment]
> PS: looking into this, I found what I believe to be a very minor issue in the `History` component factory, [here](https://github.com/aphp/edsnlp/blob/d72b2972c00382d326c782e3633a8d798ed9df97/edsnlp/pipelines/qualifiers/history/factory.py#L11), in the `DEFAULT_CONFIG`, you use not None values for `history` and `termination` but these values are useless since they are duplicates of the component's `defaults` class attribute (in the other qualifiers the corresponding parameters are correctly set to None)

Indeed, the default values are duplicated but the benefit is that they are visible from both the factory and the component class :)
