### ISSUE TITLE
Feature request: Pollution

### ISSUE THREAD

**Issue by aricohen93** [aphp/edsnlp#138]
## Feature type

Add new patterns

## Description

Add pattern to match text like :

```
2/2Pat : <NOM> <Prenom> le <date> IPP <ipp> Intitulé RCP : Urologie HMN le <date>

1/2Pat : <NOM> <Prenom> le <date> IPP <ipp> Intitulé RCP : Urologie HMN le <date>
```

**Comment by percevalw** [comment]
Hi @aricohen93, could you expand a bit more on why such a scheme would constitute pollution? It seems to me that there is a lot of useful information here!

**Comment by aricohen93** [comment]
Could be, anyway it's a footer. And it is intercalated into the text. 

So we have the following structure:

[TEXT]
[FOOTER]
[Continuation of preceding text]

**Comment by percevalw** [comment]
Completed by https://github.com/aphp/edsnlp/pull/139 and https://github.com/aphp/edsnlp/pull/150
