### ISSUE TITLE
Reason for pydantic <1.10.0

### ISSUE THREAD

**Issue by strayMat** [aphp/edsnlp#164]
# Context 

I am using [pydantic factory](https://github.com/starlite-api/pydantic-factories) for my study module to generate mock data. It relies [on pydantic >=1.10](https://github.com/starlite-api/pydantic-factories/blob/main/pyproject.toml#L57). 

# Description:

edsnlp precises that pydantic should < 1.10.0 . Is there a specific reason that we do not want to accept later version of pydantic ?

**Comment by percevalw** [comment]
Hi @strayMat, thanks for letting us know about this :) Indeed there seems to be no reason for this, we will update the constraint in the next version soon to be released.

**Comment by strayMat** [comment]
Great !  thank you so much ! 🤩

(Since the PR is alrdeay merged, I close the issue, but let me know if in the future you  prefer to close this kind of issue yourself).
