### ISSUE TITLE
Installation issues on mac M1/M2 with python 3.9

### ISSUE THREAD

**Issue by louni-g** [aphp/edsnlp#206]
## Description

An error occurs when pip installing edsnlp with python 3.9 on mac M1/M2. It can't be reproduced on intel processors, and it works with python 3.10. Here is the tail of the error: 
```
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Full log [here](https://github.com/aphp/edsnlp/files/11341769/log.1.txt)

It could be caused by the version of numpy required that is not compatible with M1/M2 processors 

## How to reproduce the bug

Run `pip install edsnlp` on a python3.9 env, on mac M1/M2

## Your Environment

- Operating System: macos
- Python Version Used: 3.9
- EDS-NLP Version Used: 0.7.4

**Comment by percevalw** [comment]
Hi, this should be fixed in the newly released v0.8.0 ! Feel free to reopen if necessary
