### ISSUE TITLE
Add to doc

### ISSUE THREAD

**Issue by aricohen93** [aphp/edsnlp#240]
## Feature type

https://github.com/aphp/edsnlp/blob/master/edsnlp/pipes/misc/sections/sections.py#L199C28-L199C28

## Description

Add this feature to the doc

**Comment by percevalw** [comment]
Actually it's already in the docs : https://aphp.github.io/edsnlp/latest/pipes/misc/sections/#edsnlp.pipes.misc.sections.factory.create_component--examples
