### ISSUE TITLE
Connectors not working [brat, json] & training issues

### ISSUE THREAD

**Issue by aricohen93** [aphp/edsnlp#242]
## Description

Problems:
- path when is a str 
- should specify sdpan_getter (also when is about ents)
- could not read annotations

## How to reproduce the bug

this example is not working
https://aphp.github.io/edsnlp/v0.10.2/data/standoff/

**Comment by aricohen93** [comment]
span_attributes could not be boolean or int

**Comment by aricohen93** [comment]
edsnlp.data.write_json([doc], "path/to/json/dir", converter="omop") >> il faut mettre un fichier, et pas un dir

**Comment by aricohen93** [comment]
json : 
lines = False ça marche pas avec plusieurs docs

**Comment by aricohen93** [comment]
so, path is a path to dir or file in function of lines argument

**Comment by aricohen93** [comment]
https://aphp.github.io/edsnlp/v0.10.2/tutorials/make-a-training-script/#6-looping-through-the-training-data

```python

 output = component.module_forward(batch[component.name]) >> replace by batch[name]
```

**Comment by aricohen93** [comment]
nlp.save("model") > ne marche pas

**Comment by percevalw** [comment]
Hello, can you paste here the traceback of some of the errors you got please ?
