### ISSUE TITLE
Include negation in tobacco and alcohol pipelines

### ISSUE THREAD

**Issue by marieverdoux** [aphp/edsnlp#287]
With the current code, detailed status "ABSENT" is assigned only when negation is found after the entity, not before.

Example: 
If text is "Patient non fumeur", detailed_status is assigned to PRESENT.
If text is "Fumeur: non" , detailed_status is assigned to ABSENT.

Feature suggestion: 
The negation patterns from negation pipelines should be included to the tobacco/alcohol pipelines so detailed_status is set to ABSENT in any negation case.

**Comment by Thomzoy** [comment]
@marieverdoux You can go ahead and test this updated version
