### ISSUE TITLE
Not expected behavior on spaces in the measures module

### ISSUE THREAD

**Issue by gozat** [aphp/edsnlp#66]
## Description

While modifying the measure module (see https://github.com/gozat/edsnlp/tree/59-more-measurements), I find that a string like `12 m 45` is not completely detected : only `12.0m` is detected. It seems it comes from the REGEX generation, that puts a `\\s*` in the pattern generated by `pipelines.misc.measures.measures.make_patterns`, and then not matching the space ; `12 m45` still produces `12.5m` as string of `span._.value`.

I wonder whether this bug is reproducible or not ? 

*I'll update this issue when I have more clue about it, sorry for this short introduction.*

**Comment by percevalw** [comment]
I'm on it, I will soon push a new version of this pipeline to fix multiple cases of false positives and false negatives such as:
- `Poids: 58` (no unit false negative)
- `perte de 8kg` (loss, false positive)
- `8g/l` (wrong unit, false positive)
- ...

**Comment by percevalw** [comment]
Hi @gozat, sorry for the delay : this bug has been fixed in the last version 0.0.6 of the library as part of the measurements refactoring of https://github.com/aphp/edsnlp/pull/21 !
