### ISSUE TITLE
Feature request: smarter reported_speech

### ISSUE THREAD

**Issue by MohamedBsh** [aphp/edsnlp#67]
## Feature type

Detect all the entities made by the patient, not by another person .

## Description

According to the documentation [doc](https://github.com/aphp/edsnlp/blob/af7de02564bb2b3233147c877cf933aacc887113/docs/pipelines/qualifiers/reported-speech.md), I thought that eds.reported_speech allowed to detect all the entities that refer to the patient, and not to the "son", "brother" or "sister .." of the patient. 

```python
import spacy
nlp = spacy.blank("fr")
nlp.add_pipe("eds.sentences")

nlp.add_pipe("eds.matcher",config=dict(terms=dict(patient="patient", alcool="alcoolisé",inconscience="inconscient")),)
nlp.add_pipe("eds.reported_speech")

text = ("Le patient est admis aux urgences ce soir après un grave accident de voiture. Il nie être inconscient. Il se plaint d'une douleur au cou, au bras gauche et au dos. Suspicion d'un traumatisme crânien. Le fils du patient était au volant. Il nie être alcoolisé.")
doc = nlp(text)
In: doc.ents
Out: (patient, inconscient, patient, alcoolisé)
In: doc.ents[0]._.reported_speech
Out: False
In: doc.ents[1]._.reported_speech
Out: True
In: doc.ents[2]._.reported_speech
Out: False
In: doc.ents[3]._.reported_speech
Out: True # False ?
```

It is interesting to use the dependency parse tree from the "patient" node (use appos, flat:name or conj .. cf [spacy linguistic features](https://spacy.io/usage/linguistic-features)) to make sure that "alcoolisé" doesn't refers to "patient".

For *Le fils du patient*, we have a "nmod" relationship: 
    *fils* <--nmod--> *patient*
that refer to the root "patient" node _"Le patient est admis .."_

At the least, we should exclude nmod relationship to detect only the entities made by the patient.

**Comment by bdura** [comment]
Hello @MohamedBsh, thanks for the input! There _might_ be a slight confusion there: the `eds.reported_speech` pipeline's aim is to detect when the caregiver **quotes the patient**. 

I think the behaviour you're looking for is achieved by the `eds.family` pipeline, although it only looks for family members. It **will** be renamed and modified to account for other types of experiencers (`eds.experiencer`?). This has been a long time coming, I'll create a feature request to reflect that.

Using a parse tree is definitely a good idea, and has been in the depths of our backlog for some time. An efficient parser would be a great way to provide very good baselines to many other problems (`eds.negation` and other qualifiers pop to mind). The one limitation with this approach would be training. Do you have any idea how a parser pre-trained on non-clinical documents fares in our setting? I'll open another issue to discuss this further!

**Comment by bdura** [comment]
I'm closing this issue, feel free to re-open it if something's missing!
