### ISSUE TITLE
[Numpy version] Incompatibility version with scikit-eds

### ISSUE THREAD

**Issue by JCharline** [aphp/edsnlp#97]
## Description

edsnlp requires a version of numpy >= 1.21 whereas scikit-eds requires numpy < 1.20 (probably due to pyspark issues).

## How to reproduce the bug
`requirements.txt` from edsnlp [here](https://github.com/aphp/edsnlp/blob/master/requirements.txt)
`requirements.txt` from scikit:
```
pgpasslib
psycopg2-binary
pandas
numpy<1.20.0  # https://github.com/databricks/koalas/pull/2166
koalas
altair
loguru
```

## Your Environment

- Operating System: Windows 10
- Python Version Used: 3.7
- spaCy Version Used: 3.31
- EDS-NLP Version Used: 0.6.0
- scikit-eds Version Used: 0.1.0

**Comment by SamirPS** [comment]
does edsnlp really need numpy 1.21 or numpy < 1.20 is enough N

**Comment by SamirPS** [comment]
> does edsnlp really need numpy 1.21 or numpy < 1.20 is enough ?

@percevalw

**Comment by percevalw** [comment]
This was a hacky fix because of some numpy C header issues, but it didn't work well in practice.

I'm closing this issue as it has been solved by https://github.com/aphp/edsnlp/pull/109, thanks again for opening the issue !
